// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RcppDist4Vec
double RcppDist4Vec(const Rcpp::NumericVector& v1, const Rcpp::NumericVector& v2, std::string method, bool na_rm);
RcppExport SEXP _infosp_RcppDist4Vec(SEXP v1SEXP, SEXP v2SEXP, SEXP methodSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDist4Vec(v1, v2, method, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppDist4Mat
Rcpp::NumericVector RcppDist4Mat(const Rcpp::NumericMatrix& mat, std::string method, bool na_rm);
RcppExport SEXP _infosp_RcppDist4Mat(SEXP matSEXP, SEXP methodSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDist4Mat(mat, method, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppDist4MatSub
Rcpp::NumericVector RcppDist4MatSub(const Rcpp::NumericMatrix& mat, const Rcpp::IntegerVector& lib, const Rcpp::IntegerVector& pred, std::string method, bool na_rm);
RcppExport SEXP _infosp_RcppDist4MatSub(SEXP matSEXP, SEXP libSEXP, SEXP predSEXP, SEXP methodSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type lib(libSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pred(predSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDist4MatSub(mat, lib, pred, method, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppLaggedNeighbors4Lattice
Rcpp::List RcppLaggedNeighbors4Lattice(const Rcpp::List& nb, int lag, bool cumulate);
RcppExport SEXP _infosp_RcppLaggedNeighbors4Lattice(SEXP nbSEXP, SEXP lagSEXP, SEXP cumulateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< bool >::type cumulate(cumulateSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppLaggedNeighbors4Lattice(nb, lag, cumulate));
    return rcpp_result_gen;
END_RCPP
}
// RcppLaggedValues4Lattice
Rcpp::List RcppLaggedValues4Lattice(const Rcpp::NumericVector& vec, const Rcpp::List& nb, int lag);
RcppExport SEXP _infosp_RcppLaggedValues4Lattice(SEXP vecSEXP, SEXP nbSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppLaggedValues4Lattice(vec, nb, lag));
    return rcpp_result_gen;
END_RCPP
}
// RcppGenLatticeEmbedding
Rcpp::NumericMatrix RcppGenLatticeEmbedding(const Rcpp::NumericVector& vec, const Rcpp::List& nb, int E, int tau, int style);
RcppExport SEXP _infosp_RcppGenLatticeEmbedding(SEXP vecSEXP, SEXP nbSEXP, SEXP ESEXP, SEXP tauSEXP, SEXP styleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< int >::type E(ESEXP);
    Rcpp::traits::input_parameter< int >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type style(styleSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGenLatticeEmbedding(vec, nb, E, tau, style));
    return rcpp_result_gen;
END_RCPP
}
// RcppLaggedValues4Grid
Rcpp::NumericMatrix RcppLaggedValues4Grid(const Rcpp::NumericMatrix& mat, int lag);
RcppExport SEXP _infosp_RcppLaggedValues4Grid(SEXP matSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppLaggedValues4Grid(mat, lag));
    return rcpp_result_gen;
END_RCPP
}
// RcppGenGridEmbedding
Rcpp::NumericMatrix RcppGenGridEmbedding(const Rcpp::NumericMatrix& mat, int E, int tau, int style);
RcppExport SEXP _infosp_RcppGenGridEmbedding(SEXP matSEXP, SEXP ESEXP, SEXP tauSEXP, SEXP styleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type E(ESEXP);
    Rcpp::traits::input_parameter< int >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type style(styleSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGenGridEmbedding(mat, E, tau, style));
    return rcpp_result_gen;
END_RCPP
}
// RcppGenTSEmbedding
Rcpp::NumericMatrix RcppGenTSEmbedding(const Rcpp::NumericVector& vec, int E, int tau, int style);
RcppExport SEXP _infosp_RcppGenTSEmbedding(SEXP vecSEXP, SEXP ESEXP, SEXP tauSEXP, SEXP styleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< int >::type E(ESEXP);
    Rcpp::traits::input_parameter< int >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type style(styleSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGenTSEmbedding(vec, E, tau, style));
    return rcpp_result_gen;
END_RCPP
}
// RcppEntropy
double RcppEntropy(SEXP series, double base, bool na_rm);
RcppExport SEXP _infosp_RcppEntropy(SEXP seriesSEXP, SEXP baseSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type series(seriesSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppEntropy(series, base, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppJE
double RcppJE(SEXP mat, const Rcpp::IntegerVector& vars, double base, bool na_rm);
RcppExport SEXP _infosp_RcppJE(SEXP matSEXP, SEXP varsSEXP, SEXP baseSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppJE(mat, vars, base, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppCE
double RcppCE(SEXP mat, const Rcpp::IntegerVector& target, const Rcpp::IntegerVector& conds, double base, bool na_rm);
RcppExport SEXP _infosp_RcppCE(SEXP matSEXP, SEXP targetSEXP, SEXP condsSEXP, SEXP baseSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type conds(condsSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppCE(mat, target, conds, base, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppMI
double RcppMI(SEXP mat, const Rcpp::IntegerVector& target, const Rcpp::IntegerVector& interact, double base, bool na_rm);
RcppExport SEXP _infosp_RcppMI(SEXP matSEXP, SEXP targetSEXP, SEXP interactSEXP, SEXP baseSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type interact(interactSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppMI(mat, target, interact, base, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppCMI
double RcppCMI(SEXP mat, const Rcpp::IntegerVector& target, const Rcpp::IntegerVector& interact, const Rcpp::IntegerVector& conds, double base, bool na_rm);
RcppExport SEXP _infosp_RcppCMI(SEXP matSEXP, SEXP targetSEXP, SEXP interactSEXP, SEXP condsSEXP, SEXP baseSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type interact(interactSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type conds(condsSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppCMI(mat, target, interact, conds, base, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppNN4Mat
Rcpp::List RcppNN4Mat(const Rcpp::NumericMatrix& mat, int k, std::string method, bool include_self);
RcppExport SEXP _infosp_RcppNN4Mat(SEXP matSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP include_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self(include_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppNN4Mat(mat, k, method, include_self));
    return rcpp_result_gen;
END_RCPP
}
// RcppNN4MatSub
Rcpp::List RcppNN4MatSub(const Rcpp::NumericMatrix& mat, const Rcpp::IntegerVector& lib, const Rcpp::IntegerVector& pred, int k, std::string method, bool include_self);
RcppExport SEXP _infosp_RcppNN4MatSub(SEXP matSEXP, SEXP libSEXP, SEXP predSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP include_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type lib(libSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pred(predSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self(include_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppNN4MatSub(mat, lib, pred, k, method, include_self));
    return rcpp_result_gen;
END_RCPP
}
// RcppNN4DistMat
Rcpp::List RcppNN4DistMat(const Rcpp::NumericMatrix& distmat, int k, bool include_self);
RcppExport SEXP _infosp_RcppNN4DistMat(SEXP distmatSEXP, SEXP kSEXP, SEXP include_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type distmat(distmatSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self(include_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppNN4DistMat(distmat, k, include_self));
    return rcpp_result_gen;
END_RCPP
}
// RcppNN4DistMatSub
Rcpp::List RcppNN4DistMatSub(const Rcpp::NumericMatrix& distmat, const Rcpp::IntegerVector& lib, const Rcpp::IntegerVector& pred, int k, bool include_self);
RcppExport SEXP _infosp_RcppNN4DistMatSub(SEXP distmatSEXP, SEXP libSEXP, SEXP predSEXP, SEXP kSEXP, SEXP include_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type distmat(distmatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type lib(libSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pred(predSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self(include_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppNN4DistMatSub(distmat, lib, pred, k, include_self));
    return rcpp_result_gen;
END_RCPP
}
// RcppGenSignatureSpace
Rcpp::NumericMatrix RcppGenSignatureSpace(const Rcpp::NumericMatrix& mat, bool relative);
RcppExport SEXP _infosp_RcppGenSignatureSpace(SEXP matSEXP, SEXP relativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< bool >::type relative(relativeSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGenSignatureSpace(mat, relative));
    return rcpp_result_gen;
END_RCPP
}
// RcppGenPatternSpace
Rcpp::CharacterVector RcppGenPatternSpace(const Rcpp::NumericMatrix& mat, bool na_rm);
RcppExport SEXP _infosp_RcppGenPatternSpace(SEXP matSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGenPatternSpace(mat, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppCountSignProp
Rcpp::NumericVector RcppCountSignProp(const Rcpp::CharacterVector& pat1, const Rcpp::CharacterVector& pat2);
RcppExport SEXP _infosp_RcppCountSignProp(SEXP pat1SEXP, SEXP pat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type pat1(pat1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type pat2(pat2SEXP);
    rcpp_result_gen = Rcpp::wrap(RcppCountSignProp(pat1, pat2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_infosp_RcppDist4Vec", (DL_FUNC) &_infosp_RcppDist4Vec, 4},
    {"_infosp_RcppDist4Mat", (DL_FUNC) &_infosp_RcppDist4Mat, 3},
    {"_infosp_RcppDist4MatSub", (DL_FUNC) &_infosp_RcppDist4MatSub, 5},
    {"_infosp_RcppLaggedNeighbors4Lattice", (DL_FUNC) &_infosp_RcppLaggedNeighbors4Lattice, 3},
    {"_infosp_RcppLaggedValues4Lattice", (DL_FUNC) &_infosp_RcppLaggedValues4Lattice, 3},
    {"_infosp_RcppGenLatticeEmbedding", (DL_FUNC) &_infosp_RcppGenLatticeEmbedding, 5},
    {"_infosp_RcppLaggedValues4Grid", (DL_FUNC) &_infosp_RcppLaggedValues4Grid, 2},
    {"_infosp_RcppGenGridEmbedding", (DL_FUNC) &_infosp_RcppGenGridEmbedding, 4},
    {"_infosp_RcppGenTSEmbedding", (DL_FUNC) &_infosp_RcppGenTSEmbedding, 4},
    {"_infosp_RcppEntropy", (DL_FUNC) &_infosp_RcppEntropy, 3},
    {"_infosp_RcppJE", (DL_FUNC) &_infosp_RcppJE, 4},
    {"_infosp_RcppCE", (DL_FUNC) &_infosp_RcppCE, 5},
    {"_infosp_RcppMI", (DL_FUNC) &_infosp_RcppMI, 5},
    {"_infosp_RcppCMI", (DL_FUNC) &_infosp_RcppCMI, 6},
    {"_infosp_RcppNN4Mat", (DL_FUNC) &_infosp_RcppNN4Mat, 4},
    {"_infosp_RcppNN4MatSub", (DL_FUNC) &_infosp_RcppNN4MatSub, 6},
    {"_infosp_RcppNN4DistMat", (DL_FUNC) &_infosp_RcppNN4DistMat, 3},
    {"_infosp_RcppNN4DistMatSub", (DL_FUNC) &_infosp_RcppNN4DistMatSub, 5},
    {"_infosp_RcppGenSignatureSpace", (DL_FUNC) &_infosp_RcppGenSignatureSpace, 2},
    {"_infosp_RcppGenPatternSpace", (DL_FUNC) &_infosp_RcppGenPatternSpace, 2},
    {"_infosp_RcppCountSignProp", (DL_FUNC) &_infosp_RcppCountSignProp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_infosp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
