# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppDist4Vec <- function(v1, v2, method = "euclidean", na_rm = TRUE) {
    .Call(`_infosp_RcppDist4Vec`, v1, v2, method, na_rm)
}

RcppDist4Mat <- function(mat, method = "euclidean", na_rm = TRUE) {
    .Call(`_infosp_RcppDist4Mat`, mat, method, na_rm)
}

RcppDist4MatSub <- function(mat, lib, pred, method = "euclidean", na_rm = TRUE) {
    .Call(`_infosp_RcppDist4MatSub`, mat, lib, pred, method, na_rm)
}

RcppLaggedNeighbors4Lattice <- function(nb, lag = 1L, cumulate = TRUE) {
    .Call(`_infosp_RcppLaggedNeighbors4Lattice`, nb, lag, cumulate)
}

RcppLaggedValues4Lattice <- function(vec, nb, lag = 1L) {
    .Call(`_infosp_RcppLaggedValues4Lattice`, vec, nb, lag)
}

RcppGenLatticeEmbedding <- function(vec, nb, E = 3L, tau = 1L, style = 1L) {
    .Call(`_infosp_RcppGenLatticeEmbedding`, vec, nb, E, tau, style)
}

RcppLaggedValues4Grid <- function(mat, lag = 1L) {
    .Call(`_infosp_RcppLaggedValues4Grid`, mat, lag)
}

RcppGenGridEmbedding <- function(mat, E = 3L, tau = 1L, style = 1L) {
    .Call(`_infosp_RcppGenGridEmbedding`, mat, E, tau, style)
}

RcppGenTSEmbedding <- function(vec, E = 3L, tau = 1L, style = 0L) {
    .Call(`_infosp_RcppGenTSEmbedding`, vec, E, tau, style)
}

RcppEntropy <- function(series, base = 2.0, na_rm = TRUE) {
    .Call(`_infosp_RcppEntropy`, series, base, na_rm)
}

RcppJE <- function(mat, vars, base = 2.0, na_rm = TRUE) {
    .Call(`_infosp_RcppJE`, mat, vars, base, na_rm)
}

RcppCE <- function(mat, target, conds, base = 2.0, na_rm = TRUE) {
    .Call(`_infosp_RcppCE`, mat, target, conds, base, na_rm)
}

RcppMI <- function(mat, target, interact, base = 2.0, na_rm = TRUE) {
    .Call(`_infosp_RcppMI`, mat, target, interact, base, na_rm)
}

RcppCMI <- function(mat, target, interact, conds, base = 2.0, na_rm = TRUE) {
    .Call(`_infosp_RcppCMI`, mat, target, interact, conds, base, na_rm)
}

RcppNN4Mat <- function(mat, k, method = "euclidean", include_self = FALSE) {
    .Call(`_infosp_RcppNN4Mat`, mat, k, method, include_self)
}

RcppNN4MatSub <- function(mat, lib, pred, k, method = "euclidean", include_self = FALSE) {
    .Call(`_infosp_RcppNN4MatSub`, mat, lib, pred, k, method, include_self)
}

RcppNN4DistMat <- function(distmat, k, include_self = FALSE) {
    .Call(`_infosp_RcppNN4DistMat`, distmat, k, include_self)
}

RcppNN4DistMatSub <- function(distmat, lib, pred, k, include_self = FALSE) {
    .Call(`_infosp_RcppNN4DistMatSub`, distmat, lib, pred, k, include_self)
}

RcppGenSignatureSpace <- function(mat, relative = TRUE) {
    .Call(`_infosp_RcppGenSignatureSpace`, mat, relative)
}

RcppGenPatternSpace <- function(mat, na_rm = TRUE) {
    .Call(`_infosp_RcppGenPatternSpace`, mat, na_rm)
}

RcppCountSignProp <- function(pat1, pat2) {
    .Call(`_infosp_RcppCountSignProp`, pat1, pat2)
}

