# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppLaggedNeighbors4Lattice <- function(nb, lag = 1L, cumulate = TRUE) {
    .Call(`_infosp_RcppLaggedNeighbors4Lattice`, nb, lag, cumulate)
}

RcppLaggedValues4Lattice <- function(vec, nb, lag = 1L) {
    .Call(`_infosp_RcppLaggedValues4Lattice`, vec, nb, lag)
}

RcppGenLatticeEmbedding <- function(vec, nb, E = 3L, tau = 1L, style = 1L) {
    .Call(`_infosp_RcppGenLatticeEmbedding`, vec, nb, E, tau, style)
}

RcppLaggedValues4Grid <- function(mat, lag = 1L) {
    .Call(`_infosp_RcppLaggedValues4Grid`, mat, lag)
}

RcppGenGridEmbedding <- function(mat, E = 3L, tau = 1L, style = 1L) {
    .Call(`_infosp_RcppGenGridEmbedding`, mat, E, tau, style)
}

RcppGenTSEmbedding <- function(vec, E = 3L, tau = 1L, style = 0L) {
    .Call(`_infosp_RcppGenTSEmbedding`, vec, E, tau, style)
}

